steps:
  PCX_PCACTIVITYCONFIG-13308:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: RAW_GWC_PC_PROD_VF
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439250
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ACTIVITYCREATIONLEVEL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439251
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ACTIVITYPATTERNCODE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439252
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ACTIVITYPATTERNSTOMERGE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439253
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ASSIGNMENTGROUPTYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439254
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: ASSIGNMENTTARGET
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439255
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ASSIGNMENTTYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439256
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439257
              stepCounter: 13308
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439258
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439259
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: DEFAULTASSIGNMENTGROUP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439260
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: GWCBI___SEQVAL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439261
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439262
              stepCounter: 13308
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: ISACTIVE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439263
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: LOADCOMMANDID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439264
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439265
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: RETIRED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439266
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: SUBTYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439267
              stepCounter: 13308
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439268
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439269
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439270
              stepCounter: 13308
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439271
              stepCounter: 13308
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439272
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439273
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439274
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439275
              stepCounter: 13308
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439276
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439277
              stepCounter: 13308
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 439278
              stepCounter: 13308
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('RAW_GWC_PC_PROD_VF', 'PCX_PCACTIVITYCONFIG') }}
      name: PCX_PCACTIVITYCONFIG
      schema: ""
      sqlType: Source
      table: PCX_PCACTIVITYCONFIG
      type: sourceInput
    stepCounter: "13308"
