steps:
  PC_ILELEMENTCONFIG-13481:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: RAW_GWC_PC_PROD_VF
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444840
              stepCounter: 13481
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444841
              stepCounter: 13481
            config: {}
            dataType: BOOLEAN
            defaultValue: ""
            description: ""
            name: ENABLED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444842
              stepCounter: 13481
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: GWCBI___SEQVAL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444843
              stepCounter: 13481
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444844
              stepCounter: 13481
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: IDENTIFIER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444845
              stepCounter: 13481
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444846
              stepCounter: 13481
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: TYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444847
              stepCounter: 13481
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444848
              stepCounter: 13481
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444849
              stepCounter: 13481
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444850
              stepCounter: 13481
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444851
              stepCounter: 13481
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444852
              stepCounter: 13481
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444853
              stepCounter: 13481
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444854
              stepCounter: 13481
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444855
              stepCounter: 13481
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 444856
              stepCounter: 13481
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('RAW_GWC_PC_PROD_VF', 'PC_ILELEMENTCONFIG') }}
      name: PC_ILELEMENTCONFIG
      schema: ""
      sqlType: Source
      table: PC_ILELEMENTCONFIG
      type: sourceInput
    stepCounter: "13481"
