steps:
  PC_NOTIFICATIONCONFIG-13499:
    operation:
      database: ""
      dataset: ""
      deployEnabled: true
      description: ""
      locationID: ""
      locationName: RAW_GWC_PC_PROD_VF
      metadata:
        columns:
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445363
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ACTIONTYPE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445364
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: BEANVERSION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445365
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CATEGORY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445366
              stepCounter: 13499
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: CREATETIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445367
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: CREATEUSERID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445368
              stepCounter: 13499
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: EFFECTIVEDATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445369
              stepCounter: 13499
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: EXPIRATIONDATE
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445370
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: GWCBI___SEQVAL
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445371
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: ID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445372
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: JURISDICTION
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445373
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: LEADTIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445374
              stepCounter: 13499
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: LINEOFBUSINESS
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445375
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,2)
            defaultValue: ""
            description: ""
            name: PREMIUMINCREASETHRESHOLD
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445376
              stepCounter: 13499
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: PUBLICID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445377
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,2)
            defaultValue: ""
            description: ""
            name: RATEINCREASETHRESHOLD
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445378
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: RETIRED
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445379
              stepCounter: 13499
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: UPDATETIME
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445380
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: UPDATEUSERID
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445381
              stepCounter: 13499
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPLOC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445382
              stepCounter: 13499
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445383
              stepCounter: 13499
            config: {}
            dataType: TIMESTAMP_NTZ(9)
            defaultValue: ""
            description: ""
            name: HVRCAPTSTAMPUTC
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445384
              stepCounter: 13499
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRCAPUSER
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445385
              stepCounter: 13499
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGKEY
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445386
              stepCounter: 13499
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRINTEGSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445387
              stepCounter: 13499
            config: {}
            dataType: TIMESTAMP_LTZ(9)
            defaultValue: ""
            description: ""
            name: HVRINTEGTSTAMP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445388
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVROP
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445389
              stepCounter: 13499
            config: {}
            dataType: NUMBER(38,0)
            defaultValue: ""
            description: ""
            name: HVRTXCOUNTDOWN
            nullable: true
            primaryKey: false
            uniqueKey: false
          - acceptedValues:
              strictMatch: true
              values: []
            appliedColumnTests: {}
            columnReference:
              columnCounter: 445390
              stepCounter: 13499
            config: {}
            dataType: VARCHAR(16777216)
            defaultValue: ""
            description: ""
            name: HVRTXSEQ
            nullable: true
            primaryKey: false
            uniqueKey: false
        join:
          joinCondition: FROM {{ ref('RAW_GWC_PC_PROD_VF', 'PC_NOTIFICATIONCONFIG') }}
      name: PC_NOTIFICATIONCONFIG
      schema: ""
      sqlType: Source
      table: PC_NOTIFICATIONCONFIG
      type: sourceInput
    stepCounter: "13499"
